// Code generated by 'goexports gonum.org/v1/gonum'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Version": reflect.ValueOf(gonum.Version),
	}
}
