// Code generated by 'goexports gonum.org/v1/plot/vg/fonts'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/fonts"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/fonts"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Asset":         reflect.ValueOf(fonts.Asset),
		"AssetDir":      reflect.ValueOf(fonts.AssetDir),
		"AssetInfo":     reflect.ValueOf(fonts.AssetInfo),
		"AssetNames":    reflect.ValueOf(fonts.AssetNames),
		"MustAsset":     reflect.ValueOf(fonts.MustAsset),
		"RestoreAsset":  reflect.ValueOf(fonts.RestoreAsset),
		"RestoreAssets": reflect.ValueOf(fonts.RestoreAssets),
	}
}
