// Code generated by 'goexports gonum.org/v1/plot/palette'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/palette"
	"image/color"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/palette"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Blue":         reflect.ValueOf(palette.Blue),
		"Cyan":         reflect.ValueOf(palette.Cyan),
		"ErrNaN":       reflect.ValueOf(&palette.ErrNaN).Elem(),
		"ErrOverflow":  reflect.ValueOf(&palette.ErrOverflow).Elem(),
		"ErrUnderflow": reflect.ValueOf(&palette.ErrUnderflow).Elem(),
		"Green":        reflect.ValueOf(palette.Green),
		"HSVAModel":    reflect.ValueOf(&palette.HSVAModel).Elem(),
		"Heat":         reflect.ValueOf(palette.Heat),
		"Magenta":      reflect.ValueOf(palette.Magenta),
		"Radial":       reflect.ValueOf(palette.Radial),
		"Rainbow":      reflect.ValueOf(palette.Rainbow),
		"Red":          reflect.ValueOf(palette.Red),
		"Reverse":      reflect.ValueOf(palette.Reverse),
		"Yellow":       reflect.ValueOf(palette.Yellow),

		// type definitions
		"ColorMap":          reflect.ValueOf((*palette.ColorMap)(nil)),
		"DivergingColorMap": reflect.ValueOf((*palette.DivergingColorMap)(nil)),
		"DivergingPalette":  reflect.ValueOf((*palette.DivergingPalette)(nil)),
		"HSVA":              reflect.ValueOf((*palette.HSVA)(nil)),
		"Hue":               reflect.ValueOf((*palette.Hue)(nil)),
		"Palette":           reflect.ValueOf((*palette.Palette)(nil)),

		// interface wrapper definitions
		"_ColorMap":          reflect.ValueOf((*_gonum_org_v1_plot_palette_ColorMap)(nil)),
		"_DivergingColorMap": reflect.ValueOf((*_gonum_org_v1_plot_palette_DivergingColorMap)(nil)),
		"_DivergingPalette":  reflect.ValueOf((*_gonum_org_v1_plot_palette_DivergingPalette)(nil)),
		"_Palette":           reflect.ValueOf((*_gonum_org_v1_plot_palette_Palette)(nil)),
	}
}

// _gonum_org_v1_plot_palette_ColorMap is an interface wrapper for ColorMap type
type _gonum_org_v1_plot_palette_ColorMap struct {
	WAlpha    func() float64
	WAt       func(a0 float64) (color.Color, error)
	WMax      func() float64
	WMin      func() float64
	WPalette  func(colors int) palette.Palette
	WSetAlpha func(a0 float64)
	WSetMax   func(a0 float64)
	WSetMin   func(a0 float64)
}

func (W _gonum_org_v1_plot_palette_ColorMap) Alpha() float64                     { return W.WAlpha() }
func (W _gonum_org_v1_plot_palette_ColorMap) At(a0 float64) (color.Color, error) { return W.WAt(a0) }
func (W _gonum_org_v1_plot_palette_ColorMap) Max() float64                       { return W.WMax() }
func (W _gonum_org_v1_plot_palette_ColorMap) Min() float64                       { return W.WMin() }
func (W _gonum_org_v1_plot_palette_ColorMap) Palette(colors int) palette.Palette {
	return W.WPalette(colors)
}
func (W _gonum_org_v1_plot_palette_ColorMap) SetAlpha(a0 float64) { W.WSetAlpha(a0) }
func (W _gonum_org_v1_plot_palette_ColorMap) SetMax(a0 float64)   { W.WSetMax(a0) }
func (W _gonum_org_v1_plot_palette_ColorMap) SetMin(a0 float64)   { W.WSetMin(a0) }

// _gonum_org_v1_plot_palette_DivergingColorMap is an interface wrapper for DivergingColorMap type
type _gonum_org_v1_plot_palette_DivergingColorMap struct {
	WAlpha            func() float64
	WAt               func(a0 float64) (color.Color, error)
	WConvergePoint    func() float64
	WMax              func() float64
	WMin              func() float64
	WPalette          func(colors int) palette.Palette
	WSetAlpha         func(a0 float64)
	WSetConvergePoint func(a0 float64)
	WSetMax           func(a0 float64)
	WSetMin           func(a0 float64)
}

func (W _gonum_org_v1_plot_palette_DivergingColorMap) Alpha() float64 { return W.WAlpha() }
func (W _gonum_org_v1_plot_palette_DivergingColorMap) At(a0 float64) (color.Color, error) {
	return W.WAt(a0)
}
func (W _gonum_org_v1_plot_palette_DivergingColorMap) ConvergePoint() float64 {
	return W.WConvergePoint()
}
func (W _gonum_org_v1_plot_palette_DivergingColorMap) Max() float64 { return W.WMax() }
func (W _gonum_org_v1_plot_palette_DivergingColorMap) Min() float64 { return W.WMin() }
func (W _gonum_org_v1_plot_palette_DivergingColorMap) Palette(colors int) palette.Palette {
	return W.WPalette(colors)
}
func (W _gonum_org_v1_plot_palette_DivergingColorMap) SetAlpha(a0 float64) { W.WSetAlpha(a0) }
func (W _gonum_org_v1_plot_palette_DivergingColorMap) SetConvergePoint(a0 float64) {
	W.WSetConvergePoint(a0)
}
func (W _gonum_org_v1_plot_palette_DivergingColorMap) SetMax(a0 float64) { W.WSetMax(a0) }
func (W _gonum_org_v1_plot_palette_DivergingColorMap) SetMin(a0 float64) { W.WSetMin(a0) }

// _gonum_org_v1_plot_palette_DivergingPalette is an interface wrapper for DivergingPalette type
type _gonum_org_v1_plot_palette_DivergingPalette struct {
	WColors        func() []color.Color
	WCriticalIndex func() (low int, high int)
}

func (W _gonum_org_v1_plot_palette_DivergingPalette) Colors() []color.Color { return W.WColors() }
func (W _gonum_org_v1_plot_palette_DivergingPalette) CriticalIndex() (low int, high int) {
	return W.WCriticalIndex()
}

// _gonum_org_v1_plot_palette_Palette is an interface wrapper for Palette type
type _gonum_org_v1_plot_palette_Palette struct {
	WColors func() []color.Color
}

func (W _gonum_org_v1_plot_palette_Palette) Colors() []color.Color { return W.WColors() }
