// Code generated by 'goexports gonum.org/v1/gonum/graph/formats/dot'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/formats/dot"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/formats/dot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Parse":       reflect.ValueOf(dot.Parse),
		"ParseBytes":  reflect.ValueOf(dot.ParseBytes),
		"ParseFile":   reflect.ValueOf(dot.ParseFile),
		"ParseString": reflect.ValueOf(dot.ParseString),
	}
}
