// Code generated by 'goexports gonum.org/v1/plot/vg/draw'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/draw"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Crop":               reflect.ValueOf(draw.Crop),
		"New":                reflect.ValueOf(draw.New),
		"NewCanvas":          reflect.ValueOf(draw.NewCanvas),
		"NewFormattedCanvas": reflect.ValueOf(draw.NewFormattedCanvas),
		"XCenter":            reflect.ValueOf(draw.XCenter),
		"XLeft":              reflect.ValueOf(draw.XLeft),
		"XRight":             reflect.ValueOf(draw.XRight),
		"YBottom":            reflect.ValueOf(draw.YBottom),
		"YCenter":            reflect.ValueOf(draw.YCenter),
		"YTop":               reflect.ValueOf(draw.YTop),

		// type definitions
		"BoxGlyph":      reflect.ValueOf((*draw.BoxGlyph)(nil)),
		"Canvas":        reflect.ValueOf((*draw.Canvas)(nil)),
		"CircleGlyph":   reflect.ValueOf((*draw.CircleGlyph)(nil)),
		"CrossGlyph":    reflect.ValueOf((*draw.CrossGlyph)(nil)),
		"GlyphDrawer":   reflect.ValueOf((*draw.GlyphDrawer)(nil)),
		"GlyphStyle":    reflect.ValueOf((*draw.GlyphStyle)(nil)),
		"LineStyle":     reflect.ValueOf((*draw.LineStyle)(nil)),
		"PlusGlyph":     reflect.ValueOf((*draw.PlusGlyph)(nil)),
		"PyramidGlyph":  reflect.ValueOf((*draw.PyramidGlyph)(nil)),
		"RingGlyph":     reflect.ValueOf((*draw.RingGlyph)(nil)),
		"SquareGlyph":   reflect.ValueOf((*draw.SquareGlyph)(nil)),
		"TextStyle":     reflect.ValueOf((*draw.TextStyle)(nil)),
		"Tiles":         reflect.ValueOf((*draw.Tiles)(nil)),
		"TriangleGlyph": reflect.ValueOf((*draw.TriangleGlyph)(nil)),
		"XAlignment":    reflect.ValueOf((*draw.XAlignment)(nil)),
		"YAlignment":    reflect.ValueOf((*draw.YAlignment)(nil)),

		// interface wrapper definitions
		"_GlyphDrawer": reflect.ValueOf((*_gonum_org_v1_plot_vg_draw_GlyphDrawer)(nil)),
	}
}

// _gonum_org_v1_plot_vg_draw_GlyphDrawer is an interface wrapper for GlyphDrawer type
type _gonum_org_v1_plot_vg_draw_GlyphDrawer struct {
	WDrawGlyph func(a0 *draw.Canvas, a1 draw.GlyphStyle, a2 vg.Point)
}

func (W _gonum_org_v1_plot_vg_draw_GlyphDrawer) DrawGlyph(a0 *draw.Canvas, a1 draw.GlyphStyle, a2 vg.Point) {
	W.WDrawGlyph(a0, a1, a2)
}
