// Code generated by 'goexports gonum.org/v1/gonum/spatial/r1'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/spatial/r1"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/spatial/r1"] = map[string]reflect.Value{
		// type definitions
		"Interval": reflect.ValueOf((*r1.Interval)(nil)),
	}
}
