// Code generated by 'goexports github.com/tobgu/qframe/aggregation'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"github.com/tobgu/qframe/aggregation"
	"reflect"
)

func init() {
	Symbols["github.com/tobgu/qframe/aggregation"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"StrJoin": reflect.ValueOf(aggregation.StrJoin),
	}
}
