// Code generated by 'goexports gonum.org/v1/gonum/graph/formats/gexf12'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/formats/gexf12"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/formats/gexf12"] = map[string]reflect.Value{
		// type definitions
		"AttValue":   reflect.ValueOf((*gexf12.AttValue)(nil)),
		"AttValues":  reflect.ValueOf((*gexf12.AttValues)(nil)),
		"Attribute":  reflect.ValueOf((*gexf12.Attribute)(nil)),
		"Attributes": reflect.ValueOf((*gexf12.Attributes)(nil)),
		"Color":      reflect.ValueOf((*gexf12.Color)(nil)),
		"Content":    reflect.ValueOf((*gexf12.Content)(nil)),
		"Edge":       reflect.ValueOf((*gexf12.Edge)(nil)),
		"Edges":      reflect.ValueOf((*gexf12.Edges)(nil)),
		"Edgeshape":  reflect.ValueOf((*gexf12.Edgeshape)(nil)),
		"Graph":      reflect.ValueOf((*gexf12.Graph)(nil)),
		"Meta":       reflect.ValueOf((*gexf12.Meta)(nil)),
		"Node":       reflect.ValueOf((*gexf12.Node)(nil)),
		"NodeShape":  reflect.ValueOf((*gexf12.NodeShape)(nil)),
		"Nodes":      reflect.ValueOf((*gexf12.Nodes)(nil)),
		"Parent":     reflect.ValueOf((*gexf12.Parent)(nil)),
		"Parents":    reflect.ValueOf((*gexf12.Parents)(nil)),
		"Position":   reflect.ValueOf((*gexf12.Position)(nil)),
		"Size":       reflect.ValueOf((*gexf12.Size)(nil)),
		"Spell":      reflect.ValueOf((*gexf12.Spell)(nil)),
		"Spells":     reflect.ValueOf((*gexf12.Spells)(nil)),
		"Thickness":  reflect.ValueOf((*gexf12.Thickness)(nil)),
	}
}
