// Code generated by 'goexports gonum.org/v1/gonum/spatial/r2'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/spatial/r2"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/spatial/r2"] = map[string]reflect.Value{
		// type definitions
		"Box": reflect.ValueOf((*r2.Box)(nil)),
		"Vec": reflect.ValueOf((*r2.Vec)(nil)),
	}
}
