// Code generated by 'goexports gonum.org/v1/gonum/stat/mds'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/stat/mds"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/stat/mds"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"TorgersonScaling": reflect.ValueOf(mds.TorgersonScaling),
	}
}
