// Code generated by 'goexports gonum.org/v1/gonum/spatial/r3'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/spatial/r3"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/spatial/r3"] = map[string]reflect.Value{
		// type definitions
		"Box": reflect.ValueOf((*r3.Box)(nil)),
		"Vec": reflect.ValueOf((*r3.Vec)(nil)),
	}
}
