// Code generated by 'goexports github.com/tobgu/qframe/function'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"github.com/tobgu/qframe/function"
	"reflect"
)

func init() {
	Symbols["github.com/tobgu/qframe/function"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AbsI":    reflect.ValueOf(function.AbsI),
		"AndB":    reflect.ValueOf(function.AndB),
		"BoolI":   reflect.ValueOf(function.BoolI),
		"ConcatS": reflect.ValueOf(function.ConcatS),
		"DivF":    reflect.ValueOf(function.DivF),
		"DivI":    reflect.ValueOf(function.DivI),
		"FloatI":  reflect.ValueOf(function.FloatI),
		"IntB":    reflect.ValueOf(function.IntB),
		"IntF":    reflect.ValueOf(function.IntF),
		"LenS":    reflect.ValueOf(function.LenS),
		"LowerS":  reflect.ValueOf(&function.LowerS).Elem(),
		"MinusF":  reflect.ValueOf(function.MinusF),
		"MinusI":  reflect.ValueOf(function.MinusI),
		"MulF":    reflect.ValueOf(function.MulF),
		"MulI":    reflect.ValueOf(function.MulI),
		"NandB":   reflect.ValueOf(function.NandB),
		"NotB":    reflect.ValueOf(function.NotB),
		"OrB":     reflect.ValueOf(function.OrB),
		"PlusF":   reflect.ValueOf(function.PlusF),
		"PlusI":   reflect.ValueOf(function.PlusI),
		"StrB":    reflect.ValueOf(function.StrB),
		"StrF":    reflect.ValueOf(function.StrF),
		"StrI":    reflect.ValueOf(function.StrI),
		"StrS":    reflect.ValueOf(function.StrS),
		"UpperS":  reflect.ValueOf(&function.UpperS).Elem(),
		"XorB":    reflect.ValueOf(function.XorB),
	}
}
