// Code generated by 'goexports gonum.org/v1/plot/vg/recorder'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/recorder"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/recorder"] = map[string]reflect.Value{
		// type definitions
		"Action":       reflect.ValueOf((*recorder.Action)(nil)),
		"Canvas":       reflect.ValueOf((*recorder.Canvas)(nil)),
		"Comment":      reflect.ValueOf((*recorder.Comment)(nil)),
		"Commenter":    reflect.ValueOf((*recorder.Commenter)(nil)),
		"DrawImage":    reflect.ValueOf((*recorder.DrawImage)(nil)),
		"Fill":         reflect.ValueOf((*recorder.Fill)(nil)),
		"FillString":   reflect.ValueOf((*recorder.FillString)(nil)),
		"Pop":          reflect.ValueOf((*recorder.Pop)(nil)),
		"Push":         reflect.ValueOf((*recorder.Push)(nil)),
		"Rotate":       reflect.ValueOf((*recorder.Rotate)(nil)),
		"Scale":        reflect.ValueOf((*recorder.Scale)(nil)),
		"SetColor":     reflect.ValueOf((*recorder.SetColor)(nil)),
		"SetLineDash":  reflect.ValueOf((*recorder.SetLineDash)(nil)),
		"SetLineWidth": reflect.ValueOf((*recorder.SetLineWidth)(nil)),
		"Stroke":       reflect.ValueOf((*recorder.Stroke)(nil)),
		"Translate":    reflect.ValueOf((*recorder.Translate)(nil)),

		// interface wrapper definitions
		"_Action":    reflect.ValueOf((*_gonum_org_v1_plot_vg_recorder_Action)(nil)),
		"_Commenter": reflect.ValueOf((*_gonum_org_v1_plot_vg_recorder_Commenter)(nil)),
	}
}

// _gonum_org_v1_plot_vg_recorder_Action is an interface wrapper for Action type
type _gonum_org_v1_plot_vg_recorder_Action struct {
	WApplyTo func(a0 vg.Canvas)
	WCall    func() string
}

func (W _gonum_org_v1_plot_vg_recorder_Action) ApplyTo(a0 vg.Canvas) { W.WApplyTo(a0) }
func (W _gonum_org_v1_plot_vg_recorder_Action) Call() string         { return W.WCall() }

// _gonum_org_v1_plot_vg_recorder_Commenter is an interface wrapper for Commenter type
type _gonum_org_v1_plot_vg_recorder_Commenter struct {
	WComment func(a0 string)
}

func (W _gonum_org_v1_plot_vg_recorder_Commenter) Comment(a0 string) { W.WComment(a0) }
