// Code generated by 'goexports github.com/tobgu/qframe/qerrors'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"github.com/tobgu/qframe/qerrors"
	"reflect"
)

func init() {
	Symbols["github.com/tobgu/qframe/qerrors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":       reflect.ValueOf(qerrors.New),
		"Propagate": reflect.ValueOf(qerrors.Propagate),

		// type definitions
		"Error": reflect.ValueOf((*qerrors.Error)(nil)),
	}
}
