// Code generated by 'goexports gonum.org/v1/plot/plotter'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/plotter"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/plotter"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckFloats":              reflect.ValueOf(plotter.CheckFloats),
		"CopyValues":               reflect.ValueOf(plotter.CopyValues),
		"CopyXYZs":                 reflect.ValueOf(plotter.CopyXYZs),
		"CopyXYs":                  reflect.ValueOf(plotter.CopyXYs),
		"DefaultCapWidth":          reflect.ValueOf(&plotter.DefaultCapWidth).Elem(),
		"DefaultFont":              reflect.ValueOf(&plotter.DefaultFont).Elem(),
		"DefaultFontSize":          reflect.ValueOf(&plotter.DefaultFontSize).Elem(),
		"DefaultGlyphStyle":        reflect.ValueOf(&plotter.DefaultGlyphStyle).Elem(),
		"DefaultGridLineStyle":     reflect.ValueOf(&plotter.DefaultGridLineStyle).Elem(),
		"DefaultLineStyle":         reflect.ValueOf(&plotter.DefaultLineStyle).Elem(),
		"DefaultQuartMedianStyle":  reflect.ValueOf(&plotter.DefaultQuartMedianStyle).Elem(),
		"DefaultQuartWhiskerStyle": reflect.ValueOf(&plotter.DefaultQuartWhiskerStyle).Elem(),
		"ErrInfinity":              reflect.ValueOf(&plotter.ErrInfinity).Elem(),
		"ErrNaN":                   reflect.ValueOf(&plotter.ErrNaN).Elem(),
		"ErrNoData":                reflect.ValueOf(&plotter.ErrNoData).Elem(),
		"MidStep":                  reflect.ValueOf(plotter.MidStep),
		"NewBarChart":              reflect.ValueOf(plotter.NewBarChart),
		"NewBoxPlot":               reflect.ValueOf(plotter.NewBoxPlot),
		"NewContour":               reflect.ValueOf(plotter.NewContour),
		"NewField":                 reflect.ValueOf(plotter.NewField),
		"NewFunction":              reflect.ValueOf(plotter.NewFunction),
		"NewGlyphBoxes":            reflect.ValueOf(plotter.NewGlyphBoxes),
		"NewGrid":                  reflect.ValueOf(plotter.NewGrid),
		"NewHeatMap":               reflect.ValueOf(plotter.NewHeatMap),
		"NewHist":                  reflect.ValueOf(plotter.NewHist),
		"NewHistogram":             reflect.ValueOf(plotter.NewHistogram),
		"NewImage":                 reflect.ValueOf(plotter.NewImage),
		"NewLabels":                reflect.ValueOf(plotter.NewLabels),
		"NewLine":                  reflect.ValueOf(plotter.NewLine),
		"NewLinePoints":            reflect.ValueOf(plotter.NewLinePoints),
		"NewPolygon":               reflect.ValueOf(plotter.NewPolygon),
		"NewQuartPlot":             reflect.ValueOf(plotter.NewQuartPlot),
		"NewSankey":                reflect.ValueOf(plotter.NewSankey),
		"NewScatter":               reflect.ValueOf(plotter.NewScatter),
		"NewXErrorBars":            reflect.ValueOf(plotter.NewXErrorBars),
		"NewYErrorBars":            reflect.ValueOf(plotter.NewYErrorBars),
		"NoStep":                   reflect.ValueOf(plotter.NoStep),
		"PaletteThumbnailers":      reflect.ValueOf(plotter.PaletteThumbnailers),
		"PostStep":                 reflect.ValueOf(plotter.PostStep),
		"PreStep":                  reflect.ValueOf(plotter.PreStep),
		"Range":                    reflect.ValueOf(plotter.Range),
		"XYRange":                  reflect.ValueOf(plotter.XYRange),

		// type definitions
		"BarChart":     reflect.ValueOf((*plotter.BarChart)(nil)),
		"BoxPlot":      reflect.ValueOf((*plotter.BoxPlot)(nil)),
		"ColorBar":     reflect.ValueOf((*plotter.ColorBar)(nil)),
		"Contour":      reflect.ValueOf((*plotter.Contour)(nil)),
		"Errors":       reflect.ValueOf((*plotter.Errors)(nil)),
		"Field":        reflect.ValueOf((*plotter.Field)(nil)),
		"FieldXY":      reflect.ValueOf((*plotter.FieldXY)(nil)),
		"Flow":         reflect.ValueOf((*plotter.Flow)(nil)),
		"Function":     reflect.ValueOf((*plotter.Function)(nil)),
		"GlyphBoxes":   reflect.ValueOf((*plotter.GlyphBoxes)(nil)),
		"Grid":         reflect.ValueOf((*plotter.Grid)(nil)),
		"GridXYZ":      reflect.ValueOf((*plotter.GridXYZ)(nil)),
		"HeatMap":      reflect.ValueOf((*plotter.HeatMap)(nil)),
		"Histogram":    reflect.ValueOf((*plotter.Histogram)(nil)),
		"HistogramBin": reflect.ValueOf((*plotter.HistogramBin)(nil)),
		"Image":        reflect.ValueOf((*plotter.Image)(nil)),
		"Labeller":     reflect.ValueOf((*plotter.Labeller)(nil)),
		"Labels":       reflect.ValueOf((*plotter.Labels)(nil)),
		"Line":         reflect.ValueOf((*plotter.Line)(nil)),
		"Polygon":      reflect.ValueOf((*plotter.Polygon)(nil)),
		"QuartPlot":    reflect.ValueOf((*plotter.QuartPlot)(nil)),
		"Sankey":       reflect.ValueOf((*plotter.Sankey)(nil)),
		"Scatter":      reflect.ValueOf((*plotter.Scatter)(nil)),
		"StepKind":     reflect.ValueOf((*plotter.StepKind)(nil)),
		"ValueLabels":  reflect.ValueOf((*plotter.ValueLabels)(nil)),
		"Valuer":       reflect.ValueOf((*plotter.Valuer)(nil)),
		"Values":       reflect.ValueOf((*plotter.Values)(nil)),
		"XErrorBars":   reflect.ValueOf((*plotter.XErrorBars)(nil)),
		"XErrorer":     reflect.ValueOf((*plotter.XErrorer)(nil)),
		"XErrors":      reflect.ValueOf((*plotter.XErrors)(nil)),
		"XValues":      reflect.ValueOf((*plotter.XValues)(nil)),
		"XY":           reflect.ValueOf((*plotter.XY)(nil)),
		"XYLabeller":   reflect.ValueOf((*plotter.XYLabeller)(nil)),
		"XYLabels":     reflect.ValueOf((*plotter.XYLabels)(nil)),
		"XYValues":     reflect.ValueOf((*plotter.XYValues)(nil)),
		"XYZ":          reflect.ValueOf((*plotter.XYZ)(nil)),
		"XYZer":        reflect.ValueOf((*plotter.XYZer)(nil)),
		"XYZs":         reflect.ValueOf((*plotter.XYZs)(nil)),
		"XYer":         reflect.ValueOf((*plotter.XYer)(nil)),
		"XYs":          reflect.ValueOf((*plotter.XYs)(nil)),
		"YErrorBars":   reflect.ValueOf((*plotter.YErrorBars)(nil)),
		"YErrorer":     reflect.ValueOf((*plotter.YErrorer)(nil)),
		"YErrors":      reflect.ValueOf((*plotter.YErrors)(nil)),
		"YValues":      reflect.ValueOf((*plotter.YValues)(nil)),

		// interface wrapper definitions
		"_FieldXY":    reflect.ValueOf((*_gonum_org_v1_plot_plotter_FieldXY)(nil)),
		"_GridXYZ":    reflect.ValueOf((*_gonum_org_v1_plot_plotter_GridXYZ)(nil)),
		"_Labeller":   reflect.ValueOf((*_gonum_org_v1_plot_plotter_Labeller)(nil)),
		"_Valuer":     reflect.ValueOf((*_gonum_org_v1_plot_plotter_Valuer)(nil)),
		"_XErrorer":   reflect.ValueOf((*_gonum_org_v1_plot_plotter_XErrorer)(nil)),
		"_XYLabeller": reflect.ValueOf((*_gonum_org_v1_plot_plotter_XYLabeller)(nil)),
		"_XYZer":      reflect.ValueOf((*_gonum_org_v1_plot_plotter_XYZer)(nil)),
		"_XYer":       reflect.ValueOf((*_gonum_org_v1_plot_plotter_XYer)(nil)),
		"_YErrorer":   reflect.ValueOf((*_gonum_org_v1_plot_plotter_YErrorer)(nil)),
	}
}

// _gonum_org_v1_plot_plotter_FieldXY is an interface wrapper for FieldXY type
type _gonum_org_v1_plot_plotter_FieldXY struct {
	WDims   func() (c int, r int)
	WVector func(c int, r int) plotter.XY
	WX      func(c int) float64
	WY      func(r int) float64
}

func (W _gonum_org_v1_plot_plotter_FieldXY) Dims() (c int, r int)           { return W.WDims() }
func (W _gonum_org_v1_plot_plotter_FieldXY) Vector(c int, r int) plotter.XY { return W.WVector(c, r) }
func (W _gonum_org_v1_plot_plotter_FieldXY) X(c int) float64                { return W.WX(c) }
func (W _gonum_org_v1_plot_plotter_FieldXY) Y(r int) float64                { return W.WY(r) }

// _gonum_org_v1_plot_plotter_GridXYZ is an interface wrapper for GridXYZ type
type _gonum_org_v1_plot_plotter_GridXYZ struct {
	WDims func() (c int, r int)
	WX    func(c int) float64
	WY    func(r int) float64
	WZ    func(c int, r int) float64
}

func (W _gonum_org_v1_plot_plotter_GridXYZ) Dims() (c int, r int)   { return W.WDims() }
func (W _gonum_org_v1_plot_plotter_GridXYZ) X(c int) float64        { return W.WX(c) }
func (W _gonum_org_v1_plot_plotter_GridXYZ) Y(r int) float64        { return W.WY(r) }
func (W _gonum_org_v1_plot_plotter_GridXYZ) Z(c int, r int) float64 { return W.WZ(c, r) }

// _gonum_org_v1_plot_plotter_Labeller is an interface wrapper for Labeller type
type _gonum_org_v1_plot_plotter_Labeller struct {
	WLabel func(a0 int) string
}

func (W _gonum_org_v1_plot_plotter_Labeller) Label(a0 int) string { return W.WLabel(a0) }

// _gonum_org_v1_plot_plotter_Valuer is an interface wrapper for Valuer type
type _gonum_org_v1_plot_plotter_Valuer struct {
	WLen   func() int
	WValue func(a0 int) float64
}

func (W _gonum_org_v1_plot_plotter_Valuer) Len() int             { return W.WLen() }
func (W _gonum_org_v1_plot_plotter_Valuer) Value(a0 int) float64 { return W.WValue(a0) }

// _gonum_org_v1_plot_plotter_XErrorer is an interface wrapper for XErrorer type
type _gonum_org_v1_plot_plotter_XErrorer struct {
	WXError func(a0 int) (float64, float64)
}

func (W _gonum_org_v1_plot_plotter_XErrorer) XError(a0 int) (float64, float64) { return W.WXError(a0) }

// _gonum_org_v1_plot_plotter_XYLabeller is an interface wrapper for XYLabeller type
type _gonum_org_v1_plot_plotter_XYLabeller struct {
	WLabel func(a0 int) string
	WLen   func() int
	WXY    func(a0 int) (x float64, y float64)
}

func (W _gonum_org_v1_plot_plotter_XYLabeller) Label(a0 int) string              { return W.WLabel(a0) }
func (W _gonum_org_v1_plot_plotter_XYLabeller) Len() int                         { return W.WLen() }
func (W _gonum_org_v1_plot_plotter_XYLabeller) XY(a0 int) (x float64, y float64) { return W.WXY(a0) }

// _gonum_org_v1_plot_plotter_XYZer is an interface wrapper for XYZer type
type _gonum_org_v1_plot_plotter_XYZer struct {
	WLen func() int
	WXY  func(a0 int) (float64, float64)
	WXYZ func(a0 int) (float64, float64, float64)
}

func (W _gonum_org_v1_plot_plotter_XYZer) Len() int                               { return W.WLen() }
func (W _gonum_org_v1_plot_plotter_XYZer) XY(a0 int) (float64, float64)           { return W.WXY(a0) }
func (W _gonum_org_v1_plot_plotter_XYZer) XYZ(a0 int) (float64, float64, float64) { return W.WXYZ(a0) }

// _gonum_org_v1_plot_plotter_XYer is an interface wrapper for XYer type
type _gonum_org_v1_plot_plotter_XYer struct {
	WLen func() int
	WXY  func(a0 int) (x float64, y float64)
}

func (W _gonum_org_v1_plot_plotter_XYer) Len() int                         { return W.WLen() }
func (W _gonum_org_v1_plot_plotter_XYer) XY(a0 int) (x float64, y float64) { return W.WXY(a0) }

// _gonum_org_v1_plot_plotter_YErrorer is an interface wrapper for YErrorer type
type _gonum_org_v1_plot_plotter_YErrorer struct {
	WYError func(a0 int) (float64, float64)
}

func (W _gonum_org_v1_plot_plotter_YErrorer) YError(a0 int) (float64, float64) { return W.WYError(a0) }
