// Code generated by 'goexports gonum.org/v1/plot'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/vg/draw"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Align":       reflect.ValueOf(plot.Align),
		"DefaultFont": reflect.ValueOf(&plot.DefaultFont).Elem(),
		"New":         reflect.ValueOf(plot.New),
		"NewLegend":   reflect.ValueOf(plot.NewLegend),
		"UTCUnixTime": reflect.ValueOf(&plot.UTCUnixTime).Elem(),
		"UnixTimeIn":  reflect.ValueOf(plot.UnixTimeIn),
		"Version":     reflect.ValueOf(plot.Version),

		// type definitions
		"Axis":          reflect.ValueOf((*plot.Axis)(nil)),
		"ConstantTicks": reflect.ValueOf((*plot.ConstantTicks)(nil)),
		"DataRanger":    reflect.ValueOf((*plot.DataRanger)(nil)),
		"DefaultTicks":  reflect.ValueOf((*plot.DefaultTicks)(nil)),
		"GlyphBox":      reflect.ValueOf((*plot.GlyphBox)(nil)),
		"GlyphBoxer":    reflect.ValueOf((*plot.GlyphBoxer)(nil)),
		"InvertedScale": reflect.ValueOf((*plot.InvertedScale)(nil)),
		"Legend":        reflect.ValueOf((*plot.Legend)(nil)),
		"LinearScale":   reflect.ValueOf((*plot.LinearScale)(nil)),
		"LogScale":      reflect.ValueOf((*plot.LogScale)(nil)),
		"LogTicks":      reflect.ValueOf((*plot.LogTicks)(nil)),
		"Normalizer":    reflect.ValueOf((*plot.Normalizer)(nil)),
		"Plot":          reflect.ValueOf((*plot.Plot)(nil)),
		"Plotter":       reflect.ValueOf((*plot.Plotter)(nil)),
		"Thumbnailer":   reflect.ValueOf((*plot.Thumbnailer)(nil)),
		"Tick":          reflect.ValueOf((*plot.Tick)(nil)),
		"Ticker":        reflect.ValueOf((*plot.Ticker)(nil)),
		"TickerFunc":    reflect.ValueOf((*plot.TickerFunc)(nil)),
		"TimeTicks":     reflect.ValueOf((*plot.TimeTicks)(nil)),

		// interface wrapper definitions
		"_DataRanger":  reflect.ValueOf((*_gonum_org_v1_plot_DataRanger)(nil)),
		"_GlyphBoxer":  reflect.ValueOf((*_gonum_org_v1_plot_GlyphBoxer)(nil)),
		"_Normalizer":  reflect.ValueOf((*_gonum_org_v1_plot_Normalizer)(nil)),
		"_Plotter":     reflect.ValueOf((*_gonum_org_v1_plot_Plotter)(nil)),
		"_Thumbnailer": reflect.ValueOf((*_gonum_org_v1_plot_Thumbnailer)(nil)),
		"_Ticker":      reflect.ValueOf((*_gonum_org_v1_plot_Ticker)(nil)),
	}
}

// _gonum_org_v1_plot_DataRanger is an interface wrapper for DataRanger type
type _gonum_org_v1_plot_DataRanger struct {
	WDataRange func() (xmin float64, xmax float64, ymin float64, ymax float64)
}

func (W _gonum_org_v1_plot_DataRanger) DataRange() (xmin float64, xmax float64, ymin float64, ymax float64) {
	return W.WDataRange()
}

// _gonum_org_v1_plot_GlyphBoxer is an interface wrapper for GlyphBoxer type
type _gonum_org_v1_plot_GlyphBoxer struct {
	WGlyphBoxes func(a0 *plot.Plot) []plot.GlyphBox
}

func (W _gonum_org_v1_plot_GlyphBoxer) GlyphBoxes(a0 *plot.Plot) []plot.GlyphBox {
	return W.WGlyphBoxes(a0)
}

// _gonum_org_v1_plot_Normalizer is an interface wrapper for Normalizer type
type _gonum_org_v1_plot_Normalizer struct {
	WNormalize func(min float64, max float64, x float64) float64
}

func (W _gonum_org_v1_plot_Normalizer) Normalize(min float64, max float64, x float64) float64 {
	return W.WNormalize(min, max, x)
}

// _gonum_org_v1_plot_Plotter is an interface wrapper for Plotter type
type _gonum_org_v1_plot_Plotter struct {
	WPlot func(a0 draw.Canvas, a1 *plot.Plot)
}

func (W _gonum_org_v1_plot_Plotter) Plot(a0 draw.Canvas, a1 *plot.Plot) { W.WPlot(a0, a1) }

// _gonum_org_v1_plot_Thumbnailer is an interface wrapper for Thumbnailer type
type _gonum_org_v1_plot_Thumbnailer struct {
	WThumbnail func(c *draw.Canvas)
}

func (W _gonum_org_v1_plot_Thumbnailer) Thumbnail(c *draw.Canvas) { W.WThumbnail(c) }

// _gonum_org_v1_plot_Ticker is an interface wrapper for Ticker type
type _gonum_org_v1_plot_Ticker struct {
	WTicks func(min float64, max float64) []plot.Tick
}

func (W _gonum_org_v1_plot_Ticker) Ticks(min float64, max float64) []plot.Tick {
	return W.WTicks(min, max)
}
