// Code generated by 'goexports gonum.org/v1/plot/vg/vgsvg'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/vgsvg"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/vgsvg"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultHeight": reflect.ValueOf(vgsvg.DefaultHeight),
		"DefaultWidth":  reflect.ValueOf(vgsvg.DefaultWidth),
		"New":           reflect.ValueOf(vgsvg.New),
		"NewWith":       reflect.ValueOf(vgsvg.NewWith),
		"UseWH":         reflect.ValueOf(vgsvg.UseWH),

		// type definitions
		"Canvas": reflect.ValueOf((*vgsvg.Canvas)(nil)),
	}
}
