// Code generated by 'goexports gonum.org/v1/gonum/stat/spatial'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/stat/spatial"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/stat/spatial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetisOrdGStar": reflect.ValueOf(spatial.GetisOrdGStar),
		"GlobalMoransI": reflect.ValueOf(spatial.GlobalMoransI),
	}
}
