// Code generated by 'goexports gonum.org/v1/gonum/graph/spectral'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/spectral"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/spectral"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewLaplacian":           reflect.ValueOf(spectral.NewLaplacian),
		"NewRandomWalkLaplacian": reflect.ValueOf(spectral.NewRandomWalkLaplacian),
		"NewSymNormLaplacian":    reflect.ValueOf(spectral.NewSymNormLaplacian),

		// type definitions
		"Laplacian": reflect.ValueOf((*spectral.Laplacian)(nil)),
	}
}
