// Code generated by 'goexports gonum.org/v1/gonum/graph/product'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/product"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/product"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Cartesian":       reflect.ValueOf(product.Cartesian),
		"CoNormal":        reflect.ValueOf(product.CoNormal),
		"Lexicographical": reflect.ValueOf(product.Lexicographical),
		"Modular":         reflect.ValueOf(product.Modular),
		"ModularExt":      reflect.ValueOf(product.ModularExt),
		"Strong":          reflect.ValueOf(product.Strong),
		"Tensor":          reflect.ValueOf(product.Tensor),

		// type definitions
		"Node": reflect.ValueOf((*product.Node)(nil)),
	}
}
