// Code generated by 'goexports gonum.org/v1/gonum/integrate'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/integrate"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/integrate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Romberg":     reflect.ValueOf(integrate.Romberg),
		"Simpsons":    reflect.ValueOf(integrate.Simpsons),
		"Trapezoidal": reflect.ValueOf(integrate.Trapezoidal),
	}
}
