// Code generated by 'goexports gonum.org/v1/plot/vg/vgtex'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/vgtex"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/vgtex"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":         reflect.ValueOf(vgtex.New),
		"NewDocument": reflect.ValueOf(vgtex.NewDocument),

		// type definitions
		"Canvas": reflect.ValueOf((*vgtex.Canvas)(nil)),
	}
}
