// Code generated by 'goexports gonum.org/v1/plot/vg/vgimg'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/vgimg"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/vgimg"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultDPI":          reflect.ValueOf(vgimg.DefaultDPI),
		"DefaultHeight":       reflect.ValueOf(vgimg.DefaultHeight),
		"DefaultWidth":        reflect.ValueOf(vgimg.DefaultWidth),
		"New":                 reflect.ValueOf(vgimg.New),
		"NewWith":             reflect.ValueOf(vgimg.NewWith),
		"UseBackgroundColor":  reflect.ValueOf(vgimg.UseBackgroundColor),
		"UseDPI":              reflect.ValueOf(vgimg.UseDPI),
		"UseImage":            reflect.ValueOf(vgimg.UseImage),
		"UseImageWithContext": reflect.ValueOf(vgimg.UseImageWithContext),
		"UseWH":               reflect.ValueOf(vgimg.UseWH),

		// type definitions
		"Canvas":     reflect.ValueOf((*vgimg.Canvas)(nil)),
		"JpegCanvas": reflect.ValueOf((*vgimg.JpegCanvas)(nil)),
		"PngCanvas":  reflect.ValueOf((*vgimg.PngCanvas)(nil)),
		"TiffCanvas": reflect.ValueOf((*vgimg.TiffCanvas)(nil)),
	}
}
