// Code generated by 'goexports gonum.org/v1/gonum/lapack/gonum'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/lapack/gonum"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/lapack/gonum"] = map[string]reflect.Value{
		// type definitions
		"Implementation": reflect.ValueOf((*gonum.Implementation)(nil)),
	}
}
