// Code generated by 'goexports gonum.org/v1/gonum/unit/constant'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/unit/constant"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/unit/constant"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AtomicMass":         reflect.ValueOf(constant.AtomicMass),
		"Avogadro":           reflect.ValueOf(constant.Avogadro),
		"Boltzmann":          reflect.ValueOf(constant.Boltzmann),
		"ElectricConstant":   reflect.ValueOf(constant.ElectricConstant),
		"ElementaryCharge":   reflect.ValueOf(constant.ElementaryCharge),
		"Faraday":            reflect.ValueOf(constant.Faraday),
		"FineStructure":      reflect.ValueOf(constant.FineStructure),
		"Gravitational":      reflect.ValueOf(constant.Gravitational),
		"LightSpeedInVacuum": reflect.ValueOf(constant.LightSpeedInVacuum),
		"MagneticConstant":   reflect.ValueOf(constant.MagneticConstant),
		"Planck":             reflect.ValueOf(constant.Planck),
		"StandardGravity":    reflect.ValueOf(constant.StandardGravity),
	}
}
