// Code generated by 'goexports github.com/tobgu/qframe/contrib/gonum/qplot'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"github.com/tobgu/qframe/contrib/gonum/qplot"
	"reflect"
)

func init() {
	Symbols["github.com/tobgu/qframe/contrib/gonum/qplot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BarPlotter":       reflect.ValueOf(qplot.BarPlotter),
		"BoxPlot":          reflect.ValueOf(qplot.BoxPlot),
		"Format":           reflect.ValueOf(qplot.Format),
		"Height":           reflect.ValueOf(qplot.Height),
		"HistogramPlotter": reflect.ValueOf(qplot.HistogramPlotter),
		"LabelOfBool":      reflect.ValueOf(qplot.LabelOfBool),
		"LabelOfEnum":      reflect.ValueOf(qplot.LabelOfEnum),
		"LabelOfFloat":     reflect.ValueOf(qplot.LabelOfFloat),
		"LabelOfInt":       reflect.ValueOf(qplot.LabelOfInt),
		"LabelOfString":    reflect.ValueOf(qplot.LabelOfString),
		"Labels":           reflect.ValueOf(qplot.Labels),
		"LinePlotter":      reflect.ValueOf(qplot.LinePlotter),
		"MustNewValueFunc": reflect.ValueOf(qplot.MustNewValueFunc),
		"MustNewValuer":    reflect.ValueOf(qplot.MustNewValuer),
		"MustNewXErrorer":  reflect.ValueOf(qplot.MustNewXErrorer),
		"MustNewXYZer":     reflect.ValueOf(qplot.MustNewXYZer),
		"MustNewXYer":      reflect.ValueOf(qplot.MustNewXYer),
		"MustNewYErrorer":  reflect.ValueOf(qplot.MustNewYErrorer),
		"NewConfig":        reflect.ValueOf(qplot.NewConfig),
		"NewLabeller":      reflect.ValueOf(qplot.NewLabeller),
		"NewQPlot":         reflect.ValueOf(qplot.NewQPlot),
		"NewValueFunc":     reflect.ValueOf(qplot.NewValueFunc),
		"NewValuer":        reflect.ValueOf(qplot.NewValuer),
		"NewXErrorer":      reflect.ValueOf(qplot.NewXErrorer),
		"NewXYZer":         reflect.ValueOf(qplot.NewXYZer),
		"NewXYer":          reflect.ValueOf(qplot.NewXYer),
		"NewYErrorer":      reflect.ValueOf(qplot.NewYErrorer),
		"PNG":              reflect.ValueOf(qplot.PNG),
		"PlotConfig":       reflect.ValueOf(qplot.PlotConfig),
		"Plotter":          reflect.ValueOf(qplot.Plotter),
		"PolygonPlotter":   reflect.ValueOf(qplot.PolygonPlotter),
		"QuartPlot":        reflect.ValueOf(qplot.QuartPlot),
		"SVG":              reflect.ValueOf(qplot.SVG),
		"ScatterPlotter":   reflect.ValueOf(qplot.ScatterPlotter),
		"ValueOfFloat":     reflect.ValueOf(qplot.ValueOfFloat),
		"ValueOfInt":       reflect.ValueOf(qplot.ValueOfInt),
		"Width":            reflect.ValueOf(qplot.Width),
		"XErrorBars":       reflect.ValueOf(qplot.XErrorBars),
		"YErrorBars":       reflect.ValueOf(qplot.YErrorBars),

		// type definitions
		"BarConfig":        reflect.ValueOf((*qplot.BarConfig)(nil)),
		"BoxPlotConfig":    reflect.ValueOf((*qplot.BoxPlotConfig)(nil)),
		"Config":           reflect.ValueOf((*qplot.Config)(nil)),
		"ConfigFunc":       reflect.ValueOf((*qplot.ConfigFunc)(nil)),
		"FormatType":       reflect.ValueOf((*qplot.FormatType)(nil)),
		"HistogramConfig":  reflect.ValueOf((*qplot.HistogramConfig)(nil)),
		"LabelFunc":        reflect.ValueOf((*qplot.LabelFunc)(nil)),
		"Labeller":         reflect.ValueOf((*qplot.Labeller)(nil)),
		"LabelsConfig":     reflect.ValueOf((*qplot.LabelsConfig)(nil)),
		"LineConfig":       reflect.ValueOf((*qplot.LineConfig)(nil)),
		"PlotterFunc":      reflect.ValueOf((*qplot.PlotterFunc)(nil)),
		"PolygonConfig":    reflect.ValueOf((*qplot.PolygonConfig)(nil)),
		"QPlot":            reflect.ValueOf((*qplot.QPlot)(nil)),
		"QuartConfig":      reflect.ValueOf((*qplot.QuartConfig)(nil)),
		"ScatterConfig":    reflect.ValueOf((*qplot.ScatterConfig)(nil)),
		"ValueFunc":        reflect.ValueOf((*qplot.ValueFunc)(nil)),
		"Valuer":           reflect.ValueOf((*qplot.Valuer)(nil)),
		"XErrorBarsConfig": reflect.ValueOf((*qplot.XErrorBarsConfig)(nil)),
		"XErrorer":         reflect.ValueOf((*qplot.XErrorer)(nil)),
		"XYLabeller":       reflect.ValueOf((*qplot.XYLabeller)(nil)),
		"XYZer":            reflect.ValueOf((*qplot.XYZer)(nil)),
		"XYer":             reflect.ValueOf((*qplot.XYer)(nil)),
		"YErrorBarsConfig": reflect.ValueOf((*qplot.YErrorBarsConfig)(nil)),
		"YErrorer":         reflect.ValueOf((*qplot.YErrorer)(nil)),
	}
}
