// Code generated by 'goexports gonum.org/v1/gonum/stat/distmat'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/stat/distmat"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/stat/distmat"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewWishart": reflect.ValueOf(distmat.NewWishart),

		// type definitions
		"Wishart": reflect.ValueOf((*distmat.Wishart)(nil)),
	}
}
