// Code generated by 'goexports gonum.org/v1/gonum/graph/encoding/digraph6'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/encoding/digraph6"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/encoding/digraph6"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Encode":  reflect.ValueOf(digraph6.Encode),
		"IsValid": reflect.ValueOf(digraph6.IsValid),

		// type definitions
		"Graph": reflect.ValueOf((*digraph6.Graph)(nil)),
	}
}
