// Code generated by 'goexports gonum.org/v1/gonum/graph/formats/sigmajs'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/formats/sigmajs"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/formats/sigmajs"] = map[string]reflect.Value{
		// type definitions
		"Edge":  reflect.ValueOf((*sigmajs.Edge)(nil)),
		"Graph": reflect.ValueOf((*sigmajs.Graph)(nil)),
		"Node":  reflect.ValueOf((*sigmajs.Node)(nil)),
	}
}
