// Code generated by 'goexports gonum.org/v1/gonum/graph/flow'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/graph/flow"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/graph/flow"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dominators":    reflect.ValueOf(flow.Dominators),
		"DominatorsSLT": reflect.ValueOf(flow.DominatorsSLT),

		// type definitions
		"DominatorTree": reflect.ValueOf((*flow.DominatorTree)(nil)),
	}
}
