// Code generated by 'goexports gonum.org/v1/plot/plotutil'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/plotutil"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/plotutil"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddBoxPlots":         reflect.ValueOf(plotutil.AddBoxPlots),
		"AddErrorBars":        reflect.ValueOf(plotutil.AddErrorBars),
		"AddLinePoints":       reflect.ValueOf(plotutil.AddLinePoints),
		"AddLines":            reflect.ValueOf(plotutil.AddLines),
		"AddScatters":         reflect.ValueOf(plotutil.AddScatters),
		"AddStackedAreaPlots": reflect.ValueOf(plotutil.AddStackedAreaPlots),
		"AddXErrorBars":       reflect.ValueOf(plotutil.AddXErrorBars),
		"AddYErrorBars":       reflect.ValueOf(plotutil.AddYErrorBars),
		"Color":               reflect.ValueOf(plotutil.Color),
		"DarkColors":          reflect.ValueOf(&plotutil.DarkColors).Elem(),
		"Dashes":              reflect.ValueOf(plotutil.Dashes),
		"DefaultColors":       reflect.ValueOf(&plotutil.DefaultColors).Elem(),
		"DefaultDashes":       reflect.ValueOf(&plotutil.DefaultDashes).Elem(),
		"DefaultGlyphShapes":  reflect.ValueOf(&plotutil.DefaultGlyphShapes).Elem(),
		"MeanAndConf95":       reflect.ValueOf(plotutil.MeanAndConf95),
		"MedianAndMinMax":     reflect.ValueOf(plotutil.MedianAndMinMax),
		"NewErrorPoints":      reflect.ValueOf(plotutil.NewErrorPoints),
		"Shape":               reflect.ValueOf(plotutil.Shape),
		"SoftColors":          reflect.ValueOf(&plotutil.SoftColors).Elem(),

		// type definitions
		"ErrorPoints": reflect.ValueOf((*plotutil.ErrorPoints)(nil)),
	}
}
