// Code generated by 'goexports gonum.org/v1/plot/cmpimg'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/cmpimg"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/cmpimg"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CheckPlot":        reflect.ValueOf(cmpimg.CheckPlot),
		"Diff":             reflect.ValueOf(cmpimg.Diff),
		"Equal":            reflect.ValueOf(cmpimg.Equal),
		"GenerateTestData": reflect.ValueOf(&cmpimg.GenerateTestData).Elem(),
	}
}
