// Code generated by 'goexports gonum.org/v1/gonum/diff/fd'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/gonum/diff/fd"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/gonum/diff/fd"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Backward":       reflect.ValueOf(&fd.Backward).Elem(),
		"Backward2nd":    reflect.ValueOf(&fd.Backward2nd).Elem(),
		"Central":        reflect.ValueOf(&fd.Central).Elem(),
		"Central2nd":     reflect.ValueOf(&fd.Central2nd).Elem(),
		"CrossLaplacian": reflect.ValueOf(fd.CrossLaplacian),
		"Derivative":     reflect.ValueOf(fd.Derivative),
		"Forward":        reflect.ValueOf(&fd.Forward).Elem(),
		"Forward2nd":     reflect.ValueOf(&fd.Forward2nd).Elem(),
		"Gradient":       reflect.ValueOf(fd.Gradient),
		"Hessian":        reflect.ValueOf(fd.Hessian),
		"Jacobian":       reflect.ValueOf(fd.Jacobian),
		"Laplacian":      reflect.ValueOf(fd.Laplacian),

		// type definitions
		"Formula":          reflect.ValueOf((*fd.Formula)(nil)),
		"JacobianSettings": reflect.ValueOf((*fd.JacobianSettings)(nil)),
		"Point":            reflect.ValueOf((*fd.Point)(nil)),
		"Settings":         reflect.ValueOf((*fd.Settings)(nil)),
	}
}
