// Code generated by 'goexports gonum.org/v1/plot/palette/moreland'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/palette/moreland"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/palette/moreland"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BlackBody":          reflect.ValueOf(moreland.BlackBody),
		"ExtendedBlackBody":  reflect.ValueOf(moreland.ExtendedBlackBody),
		"ExtendedKindlmann":  reflect.ValueOf(moreland.ExtendedKindlmann),
		"Kindlmann":          reflect.ValueOf(moreland.Kindlmann),
		"NewLuminance":       reflect.ValueOf(moreland.NewLuminance),
		"NewSmoothDiverging": reflect.ValueOf(moreland.NewSmoothDiverging),
		"SmoothBlueRed":      reflect.ValueOf(moreland.SmoothBlueRed),
		"SmoothBlueTan":      reflect.ValueOf(moreland.SmoothBlueTan),
		"SmoothGreenPurple":  reflect.ValueOf(moreland.SmoothGreenPurple),
		"SmoothGreenRed":     reflect.ValueOf(moreland.SmoothGreenRed),
		"SmoothPurpleOrange": reflect.ValueOf(moreland.SmoothPurpleOrange),
	}
}
