// Code generated by 'goexports gonum.org/v1/plot/vg/vgpdf'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/vgpdf"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/vgpdf"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DPI": reflect.ValueOf(vgpdf.DPI),
		"New": reflect.ValueOf(vgpdf.New),

		// type definitions
		"Canvas": reflect.ValueOf((*vgpdf.Canvas)(nil)),
	}
}
