// Code generated by 'goexports gonum.org/v1/plot/tools/bezier'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/tools/bezier"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/tools/bezier"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(bezier.New),

		// type definitions
		"Curve": reflect.ValueOf((*bezier.Curve)(nil)),
	}
}
