// Code generated by 'goexports github.com/tobgu/qframe/types'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"github.com/tobgu/qframe/types"
	"reflect"
)

func init() {
	Symbols["github.com/tobgu/qframe/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bool":                  reflect.ValueOf(types.Bool),
		"Enum":                  reflect.ValueOf(types.Enum),
		"Float":                 reflect.ValueOf(types.Float),
		"FunctionTypeBool":      reflect.ValueOf(types.FunctionTypeBool),
		"FunctionTypeFloat":     reflect.ValueOf(types.FunctionTypeFloat),
		"FunctionTypeInt":       reflect.ValueOf(types.FunctionTypeInt),
		"FunctionTypeString":    reflect.ValueOf(types.FunctionTypeString),
		"FunctionTypeUndefined": reflect.ValueOf(types.FunctionTypeUndefined),
		"Int":                   reflect.ValueOf(types.Int),
		"None":                  reflect.ValueOf(types.None),
		"String":                reflect.ValueOf(types.String),
		"Undefined":             reflect.ValueOf(types.Undefined),

		// type definitions
		"ColumnName":           reflect.ValueOf((*types.ColumnName)(nil)),
		"DataFuncOrBuiltInId":  reflect.ValueOf((*types.DataFuncOrBuiltInId)(nil)),
		"DataSlice":            reflect.ValueOf((*types.DataSlice)(nil)),
		"DataType":             reflect.ValueOf((*types.DataType)(nil)),
		"FunctionType":         reflect.ValueOf((*types.FunctionType)(nil)),
		"SliceFuncOrBuiltInId": reflect.ValueOf((*types.SliceFuncOrBuiltInId)(nil)),

		// interface wrapper definitions
		"_DataFuncOrBuiltInId":  reflect.ValueOf((*_github_com_tobgu_qframe_types_DataFuncOrBuiltInId)(nil)),
		"_DataSlice":            reflect.ValueOf((*_github_com_tobgu_qframe_types_DataSlice)(nil)),
		"_SliceFuncOrBuiltInId": reflect.ValueOf((*_github_com_tobgu_qframe_types_SliceFuncOrBuiltInId)(nil)),
	}
}

// _github_com_tobgu_qframe_types_DataFuncOrBuiltInId is an interface wrapper for DataFuncOrBuiltInId type
type _github_com_tobgu_qframe_types_DataFuncOrBuiltInId struct {
}

// _github_com_tobgu_qframe_types_DataSlice is an interface wrapper for DataSlice type
type _github_com_tobgu_qframe_types_DataSlice struct {
}

// _github_com_tobgu_qframe_types_SliceFuncOrBuiltInId is an interface wrapper for SliceFuncOrBuiltInId type
type _github_com_tobgu_qframe_types_SliceFuncOrBuiltInId struct {
}
