// Code generated by 'goexports gonum.org/v1/plot/vg/vgeps'. DO NOT EDIT.

// +build go1.14,!go1.15

package symbols

import (
	"gonum.org/v1/plot/vg/vgeps"
	"reflect"
)

func init() {
	Symbols["gonum.org/v1/plot/vg/vgeps"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DPI":      reflect.ValueOf(vgeps.DPI),
		"New":      reflect.ValueOf(vgeps.New),
		"NewTitle": reflect.ValueOf(vgeps.NewTitle),

		// type definitions
		"Canvas": reflect.ValueOf((*vgeps.Canvas)(nil)),
	}
}
